INSERT INTO move (move_id, name, category, power, accuracy, pp, effect, type_fk)
    (UUID(), 'Absorb', 'Special', 20, 100, 25, 'User recovers half the HP inflicted on opponent.', null),
    (UUID(), 'Acid', 'Special', 40, 100, 30, 'May lower opponent\'s Special Defense.', null),
    (UUID(), 'Acid Armor', 'Status', 0, 0, 20, 'Sharply raises user\'s Defense.', null),
    (UUID(), 'Agility', 'Status', 0, 0, 30, 'Sharply raises user\'s Speed.', null),
    (UUID(), 'Amnesia', 'Status', 0, 0, 20, 'Sharply raises user\'s Special Defense.', null),
    (UUID(), 'Aurora Beam', 'Special', 65, 100, 20, 'May lower opponent\'s Attack.', null),
    (UUID(), 'Barrage', 'Physical', 15, 85, 20, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Barrier', 'Status', 0, 0, 20, 'Sharply raises user\'s Defense.', null),
    (UUID(), 'Bide', 'Physical', 0, 0, 10, 'User takes damage for two turns then strikes back double.', null),
    (UUID(), 'Bind', 'Physical', 15, 85, 20, 'Traps opponent, damaging them for 4-5 turns.', null),
    (UUID(), 'Bite', 'Physical', 60, 100, 25, 'May cause flinching.', null),
    (UUID(), 'Blizzard', 'Special', 110, 70, 5, 'May freeze opponent.', null),
    (UUID(), 'Body Slam', 'Physical', 85, 100, 15, 'May paralyze opponent.', null),
    (UUID(), 'Bone Club', 'Physical', 65, 85, 20, 'May cause flinching.', null),
    (UUID(), 'Bonemerang', 'Physical', 50, 90, 10, 'Hits twice in one turn.', null),
    (UUID(), 'Bubble', 'Special', 40, 100, 30, 'May lower opponent\'s Speed.', null),
    (UUID(), 'Bubble Beam', 'Special', 65, 100, 20, 'May lower opponent\'s Speed.', null),
    (UUID(), 'Clamp', 'Physical', 35, 85, 15, 'Traps opponent, damaging them for 4-5 turns.', null),
    (UUID(), 'Comet Punch', 'Physical', 18, 85, 15, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Confuse Ray', 'Status', 0, 100, 10, 'Confuses opponent.', null),
    (UUID(), 'Confusion', 'Special', 50, 100, 25, 'May confuse opponent.', null),
    (UUID(), 'Constrict', 'Physical', 10, 100, 35, 'May lower opponent\'s Speed by one stage.', null),
    (UUID(), 'Conversion', 'Status', 0, 0, 30, 'Changes user\'s type to that of its first move.', null),
    (UUID(), 'Counter', 'Physical', 0, 100, 20, 'When hit by a Physical Attack, user strikes back with 2x power.', null),
    (UUID(), 'Crabhammer', 'Physical', 100, 90, 10, 'High critical hit ratio.', null),
    (UUID(), 'Cut', 'Physical', 50, 95, 30, null, null),
    (UUID(), 'Defense Curl', 'Status', 0, 0, 40, 'Raises user\'s Defense.', null),
    (UUID(), 'Dig', 'Physical', 80, 100, 10, 'Digs underground on first turn, attacks on second. Can also escape from caves.', null),
    (UUID(), 'Disable', 'Status', 0, 100, 20, 'Opponent can\'t use its last attack for a few turns.', null),
    (UUID(), 'Dizzy Punch', 'Physical', 70, 100, 10, 'May confuse opponent.', null),
    (UUID(), 'Double Kick', 'Physical', 30, 100, 30, 'Hits twice in one turn.', null),
    (UUID(), 'Double Slap', 'Physical', 15, 85, 10, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Double Team', 'Status', 0, 0, 15, 'Raises user\'s Evasiveness.', null),
    (UUID(), 'Double-Edge', 'Physical', 120, 100, 15, 'User receives recoil damage.', null),
    (UUID(), 'Dragon Rage', 'Special', 0, 100, 10, 'Always inflicts 40 HP.', null),
    (UUID(), 'Dream Eater', 'Special', 100, 100, 15, 'User recovers half the HP inflicted on a sleeping opponent.', null),
    (UUID(), 'Drill Peck', 'Physical', 80, 100, 20, null, null),
    (UUID(), 'Earthquake', 'Physical', 100, 100, 10, 'Power is doubled if opponent is underground from using Dig.', null),
    (UUID(), 'Egg Bomb', 'Physical', 100, 75, 10, null, null),
    (UUID(), 'Ember', 'Special', 40, 100, 25, 'May burn opponent.', null),
    (UUID(), 'Explosion', 'Physical', 250, 100, 5, 'User faints.', null),
    (UUID(), 'Fire Blast', 'Special', 110, 85, 5, 'May burn opponent.', null),
    (UUID(), 'Fire Punch', 'Physical', 75, 100, 15, 'May burn opponent.', null),
    (UUID(), 'Fire Spin', 'Special', 35, 85, 15, 'Traps opponent, damaging them for 4-5 turns.', null),
    (UUID(), 'Fissure', 'Physical', 0, 30, 5, 'One-Hit-KO, if it hits.', null),
    (UUID(), 'Flamethower', 'Special', 90, 100, 15, 'May burn opponent.', null),
    (UUID(), 'Flash', 'Status', 0, 100, 20, 'Lowers opponent\'s Accuracy.', null),
    (UUID(), 'Fly', 'Physical', 90, 95, 15, 'Flies up on first turn, attacks on second turn.', null),
    (UUID(), 'Focus Energy', 'Status', 0, 0, 30, 'Increases critical hit ratio.', null),
    (UUID(), 'Fury Attack', 'Physical', 15, 85, 20, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Fury Swipes', 'Physical', 18, 80, 15, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Glare', 'Status', 0, 100, 30, 'Paralyzes opponent.', null),
    (UUID(), 'Growl', 'Status', 0, 100, 40, 'Lowers opponent\'s Attack.', null),
    (UUID(), 'Growth', 'Status', 0, 0, 20, 'Raises user\'s Attack and Special Attack.', null),
    (UUID(), 'Guillotine', 'Physical', 0, 30, 5, 'One-Hit-KO, if it hits', null),
    (UUID(), 'Gust', 'Special', 40, 100, 35, 'Hits Pokémon using Fly/Bounce/Sky Drop with double power.', null),
    (UUID(), 'Harden', 'Status', 0, 0, 30, 'Raises user\'s Defense.', null),
    (UUID(), 'Haze', 'Status', 0, 0, 30, 'Resets all stat changes.', null),
    (UUID(), 'Headbutt', 'Physical', 70, 100, 15, 'May cause flinching.', null),
    (UUID(), 'High Jump Kick', 'Physical', 130, 90, 10, 'If it misses, the user loses half their HP.', null),
    (UUID(), 'Horn Attack', 'Physical', 65, 100, 25, null, null),
    (UUID(), 'Horn Drill', 'Physical', 0, 30, 5, 'One-Hit-KO, if it hits.', null),
    (UUID(), 'Hydro Pump', 'Special', 110, 80, 5, null, null),
    (UUID(), 'Hyper Beam', 'Special', 150, 90, 5, 'User must recharge next turn.', null),
    (UUID(), 'Hyper Fang', 'Physical', 80, 90, 15, 'May cause flinching.', null),
    (UUID(), 'Hypnosis', 'Status', 0, 60, 20, 'Puts opponent to sleep.', null),
    (UUID(), 'Ice Beam', 'Special', 90, 100, 10, 'May freeze opponent.', null),
    (UUID(), 'Ice Punch', 'Physical', 75, 100, 15, 'May freeze opponent.', null),
    (UUID(), 'Jump Kick', 'Physical', 100, 96, 10, 'If it misses, the user loses half their HP.', null),
    (UUID(), 'Karate Chop', 'Physical', 50, 100, 25, 'High critical hit ratio.', null),
    (UUID(), 'Kinesis', 'Status', 0, 80, 15, 'Lowers opponent\'s Accuracy.', null),
    (UUID(), 'Leech Life', 'Physical', 80, 100, 10, 'User recovers half the HP inflicted on opponent.', null),
    (UUID(), 'Leech Seed', 'Status', 0, 90, 10, 'Drains HP from opponent each turn.', null),
    (UUID(), 'Leer', 'Status', 0, 100, 30, 'Lowers opponent\'s Defense.', null),
    (UUID(), 'Lick', 'Physical', 30, 100, 30, 'May paralyze opponent.', null),
    (UUID(), 'Light Screen', 'Status', 0, 0, 30, 'Halves damage from Special attacks for 5 turns.', null),
    (UUID(), 'Lovely Kiss', 'Status', 0, 75, 10, 'Puts opponent to sleep.', null),
    (UUID(), 'Low Kick', 'Physical', 0, 100, 20, 'The heavier the opponent, the stronger the attack.', null),
    (UUID(), 'Meditate', 'Status', 0, 0, 40, 'Raises user\'s Attack.', null),
    (UUID(), 'Mega Drain', 'Special', 40, 100, 15, 'User recovers half the HP inflicted on opponent.', null),
    (UUID(), 'Mega Kick', 'Physical', 120, 75, 5, null, null),
    (UUID(), 'Mega Punch', 'Physical', 80, 85, 20, null, null),
    (UUID(), 'Metronome', 'Status', 0, 0, 10, 'User performs almost any move in the game at random.', null),
    (UUID(), 'Mimic', 'Status', 0, 0, 10, 'Copies the opponent\'s last move.', null),
    (UUID(), 'Minimize', 'Status', 0, 0, 10, 'Sharply raises user\'s Evasiveness.', null),
    (UUID(), 'Mirror Move', 'Status', 0, 0, 20, 'User performs the opponent\'s last move.', null),
    (UUID(), 'Mist', 'Status', 0, 0, 30, 'User\'s stats cannot be changed for a period of time.', null),
    (UUID(), 'Night Shade', 'Special', 0, 100, 15, 'Inflicts damage equal to user\'s level.', null),
    (UUID(), 'Pay Day', 'Physical', 40, 100, 20, 'Money is earned after the battle.', null),
    (UUID(), 'Peck', 'Physical', 35, 100, 35, null, null),
    (UUID(), 'Petal Dance', 'Special', 120, 100, 10, 'User attacks for 2-3 turns but then becomes confused.', null),
    (UUID(), 'Pin Missile', 'Physical', 25, 95, 20, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Poison Gas', 'Status', 0, 90, 40, 'Poisons opponent.', null),
    (UUID(), 'Poison Powder', 'Status', 0, 75, 35, 'Poisons opponent.', null),
    (UUID(), 'Poison Sting', 'Physical', 15, 100, 35, 'May poison the opponent.', null),
    (UUID(), 'Pound', 'Physical', 40, 100, 35, null, null),
    (UUID(), 'Psybeam', 'Special', 65, 100, 20, 'May confuse opponent.', null),
    (UUID(), 'Psychic', 'Special', 90, 100, 10, 'May lower opponent\'s Special Defense.', null),
    (UUID(), 'Psywave', 'Special', 0, 100, 15, 'Inflicts damage 50-150% of user\'s level.', null),
    (UUID(), 'Quick Attack', 'Physical', 40, 100, 30, 'User attacks first.', null),
    (UUID(), 'Rage', 'Physical', 20, 100, 20, 'Raises user\'s Attack when hit.', null),
    (UUID(), 'Razor Leaf', 'Physical', 55, 95, 25, 'High critical hit ratio.', null),
    (UUID(), 'Razor Wind', 'Special', 80, 100, 10, 'Charges on first turn, attacks on second. High critical hit ratio.', null),
    (UUID(), 'Recover', 'Status', 0, 0, 5, 'User recovers half its max HP.', null),
    (UUID(), 'Reflect', 'Status', 0, 0, 20, 'Halves damage from Physical attacks for 5 turns.', null),
    (UUID(), 'Rest', 'Status', 0, 0, 5, 'User sleeps for 2 turns, but user is fully healed.', null),
    (UUID(), 'Roar', 'Status', 0, 0, 20, 'In battles, the opponent switches. In the wild, the Pokémon runs.', null),
    (UUID(), 'Rock Slide', 'Physical', 75, 90, 10, 'May cause flinching.', null),
    (UUID(), 'Rock Throw', 'Physical', 50, 90, 15, null, null),
    (UUID(), 'Rolling Kick', 'Physical', 60, 85, 15, 'May cause flinching.', null),
    (UUID(), 'Sand Attack', 'Status', 0, 100, 15, 'Lowers opponent\'s Accuracy.', null),
    (UUID(), 'Scratch', 'Physical', 40, 100, 35, null, null),
    (UUID(), 'Screech', 'Status', 0, 85, 40, 'Sharply lowers opponent\'s Defense.', null),
    (UUID(), 'Seismic Toss', 'Physical', 0, 100, 20, 'Inflicts damage equal to user\'s level.', null),
    (UUID(), 'Self-Destruct', 'Physical', 200, 100, 5, 'User faints.', null),
    (UUID(), 'Sharpen', 'Status', 0, 0, 30, 'Raises user\'s Attack.', null),
    (UUID(), 'Sing', 'Status', 0, 55, 15, 'Puts opponent to sleep.', null),
    (UUID(), 'Skull Bash', 'Physical', 130, 100, 10, 'Raises Defense on first turn, attacks on second.', null),
    (UUID(), 'Sky Attack', 'Physical', 140, 90, 5, 'Charges on first turn, attacks on second. May cause flinching. High critical hit ratio.', null),
    (UUID(), 'Slam', 'Physical', 80, 75, 20, null null),
    (UUID(), 'Slash', 'Physical', 70, 100, 20, 'High critical hit ratio.', null),
    (UUID(), 'Sleep Powder', 'Status', 0, 75, 15, 'Puts opponent to sleep.', null),
    (UUID(), 'Sludge', 'Special', 65, 100, 20, 'May poison opponent.', null),
    (UUID(), 'Smog', 'Special', 30, 70, 20, 'May poison opponent.', null),
    (UUID(), 'Smokescreen', 'Status', 0, 100, 20, 'Lowers opponent\'s Accuracy.', null),
    (UUID(), 'Soft-Boiled', 'Status', 0, 0, 5, 'User recovers half its max HP.', null),
    (UUID(), 'Solar Beam', 'Special', 120, 100, 10, 'Charges on first turn, attacks on second.', null),
    (UUID(), 'Sonic Boom', 'Special', 0, 90, 20, 'Always inflicts 20 HP.', null),
    (UUID(), 'Spike Cannon', 'Special', 20, 100, 15, 'Hits 2-5 times in one turn.', null),
    (UUID(), 'Splash', 'Status', 0, 0, 40, 'Doesn\'t do ANYTHING.', null),
    (UUID(), 'Spore', 'Status', 0, 100, 15, 'Puts opponent to sleep.', null),
    (UUID(), 'Stomp', 'Physical', 65, 100, 20, 'May cause flinching.', null),
    (UUID(), 'Strength', 'Physical', 80, 100, 15, null, null),
    (UUID(), 'String Shot', 'Status', 0, 95, 40, 'Sharply lowers opponent\'s Speed.', null),
    (UUID(), 'Struggle', 'Physical', 50, 0, 0, 'Only usable when all PP are gone. Hurts the user.', null),
    (UUID(), 'Stun Spore', 'Status', 0, 75, 30, 'Paralyzes opponent.', null),
    (UUID(), 'Submission', 'Physical', 80, 80, 20, 'User receives recoil damage.', null),
    (UUID(), 'Substitute', 'Status', 0, 0, 10, 'Uses HP to creates a decoy that takes hits.', null),
    (UUID(), 'Super Fang', 'Physical', 0, 90, 10, 'Always takes off half of the opponent\'s HP.', null),
    (UUID(), 'Supersonic', 'Status', 0, 55, 20, 'Confuses opponent.', null),
    (UUID(), 'Surf', 'Special', 90, 100, 15, 'Hits all adjacent Pokémon.', null),
    (UUID(), 'Swift', 'Special', 60, 000, 20, 'Ignores Accuracy and Evasiveness.', null),
    (UUID(), 'Swords Dance', 'Status', 0, 0, 20, 'Sharply raises user\'s Attack.', null),
    (UUID(), 'Tackle', 'Physical', 40, 100, 35, null, null),
    (UUID(), 'Tail Whip', 'Status', 0, 100, 30, 'Lowers opponent\'s Defense.', null),
    (UUID(), 'Take Down', 'Physical', 90, 85, 20, 'User receives recoil damage.', null),
    (UUID(), 'Teleport', 'Status', 0, 0, 20, 'Allows user to flee wild battles; also warps player to last PokéCenter.', null),
    (UUID(), 'Thrash', 'Physical', 120, 100, 10, 'User attacks for 2-3 turns but then becomes confused.', null),
    (UUID(), 'Thunder', 'Special', 110, 70, 10, 'May paralyze opponent.', null),
    (UUID(), 'Thunder Punch', 'Physical', 75, 100, 15, 'May paralyze opponent.', null),
    (UUID(), 'Thunder Shock', 'Special', 40, 100, 30, 'May paralyze opponent.', null),
    (UUID(), 'Thunder Wave', 'Status', 0, 90, 20, 'Paralyzes opponent.', null),
    (UUID(), 'Thunderbolt', 'Special', 90, 100, 15, 'May paralyze opponent.', null),
    (UUID(), 'Toxic', 'Status', 0, 90, 10, 'Badly poisons opponent.', null),
    (UUID(), 'Transform', 'Status', 0, 0, 10, 'User takes on the form and attacks of the opponent.', null),
    (UUID(), 'Tri Attack', 'Special', 80, 100, 10, 'May paralyze, burn or freeze opponent.', null),
    (UUID(), 'Twineedle', 'Physical', 25, 100, 20, 'Hits twice in one turn. May poison opponent.', null),
    (UUID(), 'Vine Whip', 'Physical', 45, 100, 25, null, null),
    (UUID(), 'Vise Grip', 'Physical', 55, 100, 30, null, null),
    (UUID(), 'Water gun', 'Special', 40, 100, 25, null, null),
    (UUID(), 'Waterfall', 'Physical', 80, 100, 15, 'May cause flinching.', null),
    (UUID(), 'Whirlwind', 'Status', 0, 0, 20, 'In battles, the opponent switches. In the wild, the Pokémon runs.', null),
    (UUID(), 'Wing Attack', 'Physical', 60, 100, 35, null, null),
    (UUID(), 'Withdraw', 'Status', 0, 0, 40, 'Raises user\'s Defense.', null),
    (UUID(), 'Wrap', 'Physical', 15, 90, 20, 'Traps opponent, damaging them for 4-5 turns.', null)