name: CI

on:
  push:
    branches: 
      - feature/**
  pull_request:
    branches: 
      - feature/**
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      PROFILE: production 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check and Replace Properties File
        run: |
          if [ $PROFILE == "production" ]; then
            cp -f path/to/production/application.properties path/to/application.properties
          elif [ $PROFILE == "development" ]; then
            cp -f path/to/development/application.properties path/to/application.properties
          elif [ $PROFILE == "test" ]; then
            cp -f path/to/test/application.properties path/to/application.properties
          fi

      - name: Build and Test with Maven
        run: mvn -B -f pokedex/pom.xml clean verify
